name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: admin
          POSTGRESQL_PASSWORD: password
          POSTGRESQL_DATABASE: investodb

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: npm ci

      - run: npm run test:e2e
        env:
          DATABASE_URL: "postgresql://admin:password@localhost:5432/investodb?schema=public"