name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Run typescript check
        run: yarn tsc --noEmit  

      - name: Run test
        run: yarn test